"""
Definisi tipe paket komunikasi jaringan (client <-> server).
Semua paket berupa JSON dengan struktur: {type, seq, ts, payload}.
"""


class C2S:
    """Client to Server."""
    REGISTER_REQ = "REGISTER_REQ"
    LOGIN_REQ = "LOGIN_REQ"
    SESSION_LOGIN_REQ = "SESSION_LOGIN_REQ"
    CREATE_ROOM_REQ = "CREATE_ROOM_REQ"
    JOIN_ROOM_REQ = "JOIN_ROOM_REQ"
    MATCHMAKE_REQ = "MATCHMAKE_REQ"
    START_MATCH_REQ = "START_MATCH_REQ"
    PLAY_CARD = "PLAY_CARD"
    DRAW_CARD = "DRAW_CARD"
    CALL_UNO = "CALL_UNO"
    RECONNECT_REQ = "RECONNECT_REQ"
    LEAVE_ROOM = "LEAVE_ROOM"
    PING = "PING"
    GET_LEADERBOARD = "GET_LEADERBOARD"
    GET_STATS = "GET_STATS"
    GET_TOP_GLOBAL = "GET_TOP_GLOBAL"
    GET_MATCH_HISTORY = "GET_MATCH_HISTORY"


class S2C:
    """Server to Client."""
    REGISTER_OK = "REGISTER_OK"
    REGISTER_FAIL = "REGISTER_FAIL"
    LOGIN_OK = "LOGIN_OK"
    LOGIN_FAIL = "LOGIN_FAIL"
    ROOM_CREATED = "ROOM_CREATED"
    JOIN_OK = "JOIN_OK"
    JOIN_FAIL = "JOIN_FAIL"
    MATCH_FOUND = "MATCH_FOUND"
    ROOM_UPDATE = "ROOM_UPDATE"
    GAME_START = "GAME_START"
    STATE_UPDATE = "STATE_UPDATE"
    DRAW_RESULT = "DRAW_RESULT"
    UNO_OK = "UNO_OK"
    UNO_ANNOUNCE = "UNO_ANNOUNCE"
    UNO_PENALTY = "UNO_PENALTY"
    ACTION_REJECTED = "ACTION_REJECTED"
    PLAYER_WIN = "PLAYER_WIN"
    ENTER_SPECTATOR = "ENTER_SPECTATOR"
    RECONNECT_OK = "RECONNECT_OK"
    MATCH_RESULT = "MATCH_RESULT"
    PONG = "PONG"
    LEADERBOARD = "LEADERBOARD"
    STATS = "STATS"
    TOP_GLOBAL = "TOP_GLOBAL"
    MATCH_HISTORY = "MATCH_HISTORY"
    LEFT_ROOM = "LEFT_ROOM"
    FORCE_LOGOUT = "FORCE_LOGOUT"
    DRAW_STACK_RESULT = "DRAW_STACK_RESULT"
    UNO_CATCH = "UNO_CATCH"
    ERROR = "ERROR"


# Alasan penolakan (untuk ACTION_REJECTED)
class RejectReason:
    NOT_YOUR_TURN = "not_your_turn"
    INVALID_CARD = "invalid_card"
    MUST_STACK_OR_DRAW = "must_stack_or_draw"
    SPECTATOR_CANNOT_ACT = "spectator_cannot_act"
    INVALID_PACKET = "invalid_packet"
    NOT_AUTHENTICATED = "not_authenticated"
    BAD_SEQUENCE = "bad_sequence"
    ROOM_FULL = "room_full"
    ROOM_NOT_FOUND = "room_not_found"
    NOT_HOST = "not_host"
    NOT_ENOUGH_PLAYERS = "not_enough_players"
    ALREADY_DREW = "already_drew"
